# Generated by Django 3.1.6 on 2021-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web',
            old_name='doctor',
            new_name='inquiry',
        ),
        migrations.RemoveField(
            model_name='web',
            name='date',
        ),
        migrations.RemoveField(
            model_name='web',
            name='department',
        ),
        migrations.RemoveField(
            model_name='web',
            name='phone',
        ),
        migrations.AlterField(
            model_name='web',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
