# Generated by Django 3.1.7 on 2021-02-20 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='Email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='db',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
